# SPDX-License-Identifier: GPL-2.0
# rodin r12: 6.6 的 page-pool 库（mtk_sec_heap/mtk_heap_refill 需要其导出）
obj-$(CONFIG_DMABUF_HEAPS_PAGE_POOL)	+= page_pool.o
obj-$(CONFIG_DMABUF_HEAPS_SYSTEM)	+= system_heap.o
obj-$(CONFIG_DMABUF_HEAPS_CMA)		+= cma_heap.o
