/* SPDX-License-Identifier: GPL-2.0 */
/*
 * vseq_order_gen.c —— 生成的原厂装载序表
 *   seq 0..222    = 6.6 原厂 first-stage libmodprobe 实测装载序（224 条对账一致，
 *                    tools/_b523_vseq/gen_vseq.py 生成）。
 *   seq 1000 起   = 第二十五轮收编的第二批（6.6 vendor_dlkm 后装波次，无设备实测
 *                    逐条序）；相对序 = =y 现存标准 initcall（层级, 链接址）秩，
 *                    保持前二十四轮真机已验证的两两相对序；与第一批的边界
 *                    （第二批整体后置）恢复 6.6 语义。tools/_b525_recon 生成。
 *   第二十七轮（#142）：1143-1172 相机/热簇按 6.6 真机 dmesg 实测 probe 时刻
 *                    重排（14 单元有实测；静默单元保持组内相对序；块外零改）。
 *                    合成序把 mtk_imgsys_isp8 排在 mtk_imgsys_cmdq_isp8/hcp
 *                    之前，6.6 实序相反（hcp 3.014s / cmdq 3.024s → imgsys
 *                    3.636s）；imgsys probe 的 imgsys_cmdq_init 解引用 cmdq
 *                    单元 drvdata，倒挂即 [NULL+8] 崩（#142 实证）。
 *                    tools/_b527_fix。
 *   T1 七件（2026-10-03）：miev/xm_power 用第一批实测位（seq 23/184）；
 *                    其余五件 6.6 均为后装波次 .ko、互零依赖，续编 1232+
 *                    组内字母序（tools/_t1）。
 *   T2①（2026-10-04）：binder_prio 续编 1249（6.6 装载位 vendor_dlkm
 *                    modules.load 行 248，零依赖；tools/_t2bp）。
 *   第三十八轮（#158）：sensorhub 1138→1211 挪至 scp(1210) 之后。第二批合成序
 *                    把 sensorhub 排在 scp 之前，ipi_comm_init 在 scp_ipidev
 *                    就绪前调 mtk_ipi_register 得 -1 一次性放弃，SCP 固件随后
 *                    发 IPI 32(sensor notify) 命中 pin_buf=NULL 的 recv pin，
 *                    mtk-mbox.c:562 BUG_ON 崩机。相对序对齐 stock
 *                    vendor_dlkm modules.load：scp.ko(行123) < sensorhub.ko(行145)。
 *                    tools/_b538。
 *   第三十九轮（#159）：连通性集群 1179-1189 十一单元整体挪至 scp(1210) 之后，
 *                    按 stock modules.load 136-145 段定序 connscp<connfem<
 *                    conninfra<wmt<wlan<fmradio<gps_drv；bt 按 stock 191 行
 *                    （apusys/mali 之后）置块尾；gps_scp/gps_pwr/mi_gps_pwr
 *                    无 stock 行，保持 gps_drv 后原相对序。修 connscp 倒挂致
 *                    conap IPI 34 注册死链（scp_A_register_notify 未执行→
 *                    READY 重试永不触发→pin_buf=NULL 同 IPI 32 型 BUG_ON）。
 *                    1190-1209 段顺势 -11 前移；sensorhub→1222、尾段→+11。
 *                    tools/_b539。
 *   第四十轮（#163）：scp 1210→1071 前移至音频簇（1072-1119）之前，修 A-28
 *                    声卡卡片实例化倒挂。b539 侦察：vseq 第二批序忠实复刻
 *                    stock 纸面序（声卡件 83-89 行 < scp.ko 123 行），但 6.6
 *                    实际存活靠 deferred-probe 有效序——scp probe 2.578s ≪
 *                    音频链 2.93-3.04s（机器驱动 mt6899-mt6368 2.965s 才首次
 *                    probe，零 defer 重试）。=y 重放下卡片实例化在
 *                    [299]-[311] 段 one-shot 跑完：snd_soc_component_probe
 *                    (snd-scp-ultra) 撞 scp_get_reserve_mem_phys(ULTRA_MEM_ID)
 *                    ==0 返 -1 不再 defer，card0 全程零注册（#158 实证）。
 *                    scp 二批依赖为零（mbox/clk/regulator/emi-mpu 全第一批），
 *                    前移无新倒挂；ccci_fsm_scp(1175) ready 重试自愈、
 *                    audio_ipi(1178) 运行期惰性调用、aov/aod 本机无 DT 节点。
 *                    判据 = snd_soc_register_card pss 0 + card0 注册。
 *                    tools/_b540。
 *   T2③-⑧（2026-10-04）：scene_swappiness 223/simtray 224（vendorboot 段，6.6
 *                    init/probe 2.441s/2.482s 在 libmodprobe 224 波后）；
 *                    cpu_isolate_cooling 1250/mi_exception_log 1251/
 *                    xiaomi_spi_tee 1252（vendor_dlkm 段尾续编，stock
 *                    modules.load 行 102/251/5，六件互零符号依赖，
 *                    tools/_b542_build）。
 *   第五十七轮（#186）：usb_offload 1095→1120、snd_soc_audiodsp_common
 *                    1108→1121，双双挪至 adsp_v2(1119) 之后，修 A-52。
 *                    vseq dep 符号拓扑编码不了"提供者 probe 填全局表→消费者
 *                    probe 读表"的运行时数据依赖：usb_offload probe 读 ADSP
 *                    mblock 表（adsp_reserve_mblocks，由 adsp-v2 单元
 *                    adsp_mem_device_probe 填充），符号边只指向 adsp.ko(196)
 *                    ⇒ 推演序 usb_offload(1095)<adsp_v2(1119) 与 6.6
 *                    vendor_dlkm 手排 adsp-v2.ko(71)<usb_offload.ko(73) 相反
 *                    ⇒ 重放 probe 表空 -EPROBE_DEFER ×4（8 行 ERR/开机，
 *                    deferred 队列 4.734s 自愈成功）。snd_soc_audiodsp_common
 *                    （snd-audio-dsp 同读 mblock 表）同根因同修。
 *                    跨序区间 1096-1119 预检零耦合：met_*×10/音频 soc 家族/
 *                    scp-vow 家族/tmem_ffa 与两名消费者零符号交互；
 *                    mtk_soc_offload_common(1109) 为死条目（vmlinux 仅表
 *                    rodata 字符串、System.map 零符号）；usb_offload 导出面
 *                    （mtk_offload_* 共 8 符号）=y 集内零外部调用者；
 *                    xhci_mtk=126/mtu3=127 第一波不动。tools/_b555_a52_vseqfix。
 *   第六十一轮（#236）：第二批四处相对倒挂复位 stock 序，修 A-63/A-64。
 *                    ①audio_ipi 1178→1120（与 usb_offload/jpeg_driver 共槽，
 *                    tie 由 (seq,lvl,ord) 决胜，三者零耦合）：dsp_pcm（
 *                    snd_soc_audiodsp_common=1121 成员）probe 同步逐 task 发
 *                    TASK_INIT（mtk-dsp-pcm.c dsp_pcm_dev_probe→mtk_init_
 *                    adsp_audio_share_mem→mem-control），命中 adsp_ipi_queue.c
 *                    :559 的 enable 门（队列未 enable 即静默丢包 return -1）；
 *                    enable 唯一置位在 audio_ipi init 的 ipi_queue_init
 *                    （audio_ipi.c:660）→dsp_init_single_msg_queue。audio_ipi
 *                    依赖 adsp(196) 与 adsp_v2(1119) 填的预留内存表，均在
 *                    1120 前；stock 行 72 恰在 adsp-v2(71)/usb_offload(73)
 *                    之间。usip(1072) 等对 audio_ipi 的调用运行期惰性且今天
 *                    早已倒挂，前移只减不改。
 *                    ②ccci 五行 1173-1177→1028-1032，内部序 auxadc<md_all<
 *                    ccif<dpmaif<fsm_scp（按 stock dep 实序非行序，见下）：
 *                    usip(1072，probe 尾 get_smem_phy_start_addr，
 *                    mtk-usip.c:241) 与 mddp(1074，mddp_ipc_init→md_smem_
 *                    layout_config+open_port，失败 _init_fail 抹 is_config→
 *                    wlan attach -1) 都依赖 md_all probe 填 modem_sys
 *                    （modem_sys1.c:1251）；stock 行 83/90 << 31-36。落位借
 *                    mtk_scpsys_mt6761/6781/6833/6853/mt6991_spm(1028-1032)
 *                    五个异构 SoC 死条目（无 .o、System.map 零符号、无 vseq
 *                    entry，运行时 ccci 独占；(1019,1071) 内 1020-1070 全被
 *                    活条目占用，无真空闲整数）。内部序依据 vendor_dlkm
 *                    modules.dep 实序：ccif/dpmaif/fsm_scp 硬依赖 md_all、
 *                    md_all 依赖 auxadc（md_all 的 ccci_fsm.o/port_rpc.o 调
 *                    auxadc 导出 ccci_get_adc_*），行 32-36 是 dep 前插后的
 *                    尝试序非实装序。md_all 对 pbm(1068)/mdpm(1067)/ccmni(
 *                    1126)/dynamic_loading(1054) 的 modinfo 边全运行期惰性
 *                    （kicker_pbm_by_md 在 MD 上下电、init_md_section_level
 *                    有空表守卫、ccmni_ops 为编译期初始化函数表、后两者零
 *                    符号边）；fsm_scp(1032) 在 scp(1071) 前同 stock 行序
 *                    （36<123），#163 前实机旧序 1175<1210 ready 重试自愈，
 *                    mtk_ipi(42)/mbox(40/41) 全第一批。跨序区间预检：ccci
 *                    导出的外部消费者 usip(1072)/mddp(1074)/md_power_
 *                    throttling(1055)/pmic_oc_debug(1079)/c2k_usb(1092)/
 *                    md_cooling(1150)/mbraink(1170+) 全在 1032 后，前移零新
 *                    倒挂，备选 B（后移消费者）不触发。
 *                    ③mtk_swpm_dbg_v6899 1012→1095（#186 usb_offload 让出的
 *                    空洞）：init 调 sspm_sbuf_get 早于 sspm_v3(1013) probe，
 *                    重放打 "get sspm dram addr failed"；1095>1013 修复；
 *                    nm 反查全表零外部消费者，后移无风险；qos 命令
 *                    （mtk_qos=1231）为 A-22 下游不改。
 *                    ④mtk_ccuv 1167→1138（#158 sensorhub 让出的空洞）：
 *                    相机簇（mtk_cam_isp8=1143 起）rproc_get_by_phandle 拿
 *                    ccu handle（mtk_imgsys-v4l2.c:2793，probe 一次性、NULL
 *                    即 goto out 不重试），映射要等 ccu probe 的 rproc_add
 *                    （mtk_ccu_isp71.c:1310）；stock 行 12 << 128。ccuv
 *                    dep 为零、导出符号唯一外部消费者 mmdvfs-ccu(1051) 本就
 *                    在前且惰性，相对序不变。
 *                    stock 行序锚（modules.load）：mtk_ccuv=12、ccci_util_lib
 *                    =31、五 ccci=32-36、sspm=47、ged=67、mali=70、adsp-v2=
 *                    71、audio_ipi=72、usb_offload=73、audiodsp=81、usip=83、
 *                    mddp=90、gpu_qos=104、scp=123、cam=128、swpm 族=132-135、
 *                    wlan=141、mtk_qos=150。tools/_b585_vseq_order。
 * 条目 = (归一化模块名, 序号)；runner 按此稳定排序 .vseq.entries。
 */
#include <linux/vseq.h>

const struct vseq_mod_order __vseq_mod_order[] = {
	{ .name = "bootprof", .seq = 0 },
	{ .name = "bootmonitor", .seq = 1 },
	{ .name = "mrdump", .seq = 2 },
	{ .name = "mboot_params", .seq = 2 },
	{ .name = "mrdump_control", .seq = 2 },
	{ .name = "mrdump_mini", .seq = 2 },
	{ .name = "mrdump_panic", .seq = 2 },
	{ .name = "mrdump_helper", .seq = 2 },
	{ .name = "aee_aed", .seq = 3 },
	{ .name = "aed_main", .seq = 3 },
	{ .name = "aed_debug", .seq = 3 },
	{ .name = "aee_common", .seq = 3 },
	{ .name = "slog", .seq = 3 },
	{ .name = "monitor_hang", .seq = 4 },
	{ .name = "hang_detect", .seq = 4 },
	{ .name = "hang_unwind", .seq = 4 },
	{ .name = "mkp", .seq = 5 },
	{ .name = "dbgtop_drm", .seq = 6 },
	{ .name = "irq_dbg", .seq = 7 },
	{ .name = "mtk_sync", .seq = 8 },
	{ .name = "mtk_disp_notify", .seq = 9 },
	{ .name = "zsmalloc", .seq = 10 },
	{ .name = "zram", .seq = 11 },
	{ .name = "zcomp", .seq = 11 },
	{ .name = "zram_drv", .seq = 11 },
	{ .name = "log_store", .seq = 12 },
	{ .name = "mtk_printk_ctrl", .seq = 13 },
	{ .name = "nvmem_mtk_devinfo", .seq = 14 },
	{ .name = "mtk_devinfo", .seq = 14 },
	{ .name = "mtk_wdt", .seq = 15 },
	{ .name = "timer_mediatek", .seq = 16 },
	{ .name = "aee_hangdet", .seq = 17 },
	{ .name = "hangdet", .seq = 17 },
	{ .name = "sched_debug", .seq = 17 },
	{ .name = "timer_list_debug", .seq = 17 },
	{ .name = "sec_rng", .seq = 18 },
	{ .name = "device_apc_common", .seq = 19 },
	{ .name = "device_apc_mt6899", .seq = 20 },
	{ .name = "mtk_mbox_mailbox", .seq = 21 },
	{ .name = "tinysys_scmi", .seq = 22 },
	{ .name = "tinysys_scmi_drv", .seq = 22 },
	{ .name = "tinysys", .seq = 22 },
	{ .name = "miev", .seq = 23 },
	{ .name = "wlan_page_pool", .seq = 24 },
	{ .name = "pinctrl_mtk_v2", .seq = 25 },
	{ .name = "mtk_eint", .seq = 25 },
	{ .name = "pinctrl_mtk_common_v2", .seq = 25 },
	{ .name = "pinctrl_paris", .seq = 25 },
	{ .name = "pinctrl_mt6899", .seq = 26 },
	{ .name = "mtk_iommu_util", .seq = 27 },
	{ .name = "iommu_debug", .seq = 28 },
	{ .name = "iommu_secure", .seq = 29 },
	{ .name = "mtk_smi", .seq = 30 },
	{ .name = "emi", .seq = 31 },
	{ .name = "emi_cen", .seq = 31 },
	{ .name = "emi_isu", .seq = 31 },
	{ .name = "emi_dbg", .seq = 31 },
	{ .name = "mtk_smi_dbg", .seq = 32 },
	{ .name = "mtk_iommu", .seq = 33 },
	{ .name = "mm_fake_engine", .seq = 34 },
	{ .name = "system_heap", .seq = 35 },
	{ .name = "mtk_system_heap", .seq = 35 },
	{ .name = "mtk_page_pool", .seq = 35 },
	{ .name = "mtk_cache_pool", .seq = 35 },
	{ .name = "mtk_dmabuf_monitor", .seq = 35 },
	{ .name = "mtk_deferred_free_helper", .seq = 35 },
	{ .name = "clk_common", .seq = 36 },
	{ .name = "mtk_scpsys", .seq = 37 },
	{ .name = "clk_fmeter_mt6899", .seq = 38 },
	{ .name = "vcp_status", .seq = 39 },
	{ .name = "mtk_mbox", .seq = 40 },
	{ .name = "mtk_rpmsg_mbox", .seq = 41 },
	{ .name = "mtk_tinysys_ipi", .seq = 42 },
	{ .name = "vcp", .seq = 43 },
	{ .name = "mtk_dvfsrc", .seq = 44 },
	{ .name = "mtk_dvfsrc_regulator", .seq = 45 },
	{ .name = "mtk_dvfsrc_devfreq", .seq = 46 },
	{ .name = "mtk_emi", .seq = 47 },
	{ .name = "mtk_hw_semaphore", .seq = 48 },
	{ .name = "clk_mt6899", .seq = 49 },
	{ .name = "clk_mt6899_adsp", .seq = 50 },
	{ .name = "clk_mt6899_cam", .seq = 51 },
	{ .name = "clk_mt6899_img", .seq = 52 },
	{ .name = "clk_mt6899_mmsys", .seq = 53 },
	{ .name = "clk_mt6899_peri", .seq = 54 },
	{ .name = "clk_mt6899_mdpsys", .seq = 55 },
	{ .name = "clk_mt6899_vcodec", .seq = 56 },
	{ .name = "clk_mt6899_infracfg_ao", .seq = 57 },
	{ .name = "mtk_scpsys_mt6899", .seq = 58 },
	{ .name = "mtk_scpsys_bringup", .seq = 59 },
	{ .name = "clk_bringup", .seq = 60 },
	{ .name = "clk_chk_mt6899", .seq = 61 },
	{ .name = "pd_chk_mt6899", .seq = 62 },
	{ .name = "mtk_pmic_wrap", .seq = 63 },
	{ .name = "mtk_spmi_pmic", .seq = 64 },
	{ .name = "spmi_mtk_pmif", .seq = 65 },
	{ .name = "spmi_mtk_pmif_core", .seq = 65 },
	{ .name = "spmi_mtk_debug", .seq = 65 },
	{ .name = "mt6315_regulator", .seq = 66 },
	{ .name = "mt6316_regulator", .seq = 67 },
	{ .name = "mt6363_regulator", .seq = 68 },
	{ .name = "mt6368_regulator", .seq = 69 },
	{ .name = "pinctrl_mtk_common_v2_debug", .seq = 70 },
	{ .name = "i2c_mt65xx", .seq = 71 },
	{ .name = "mt6681_regulator", .seq = 72 },
	{ .name = "mtk_dcm", .seq = 73 },
	{ .name = "mt6899_dcm", .seq = 74 },
	{ .name = "mt6899_dcm_internal", .seq = 74 },
	{ .name = "mt6899_dcm_autogen", .seq = 74 },
	{ .name = "mmprofile", .seq = 75 },
	{ .name = "mtk_mmdebug_vcp", .seq = 76 },
	{ .name = "mtk_mmdvfs_v3", .seq = 77 },
	{ .name = "mtk_dramc", .seq = 78 },
	{ .name = "dramc", .seq = 78 },
	{ .name = "dramc_bin", .seq = 78 },
	{ .name = "mtk_mmdvfs", .seq = 79 },
	{ .name = "mtk_mmdvfs_ftrace", .seq = 80 },
	{ .name = "mtk_mmdvfs_debug", .seq = 81 },
	{ .name = "mtk_dvfsrc_helper", .seq = 82 },
	{ .name = "dvfsrc_helper", .seq = 82 },
	{ .name = "dvfsrc_debug_v3", .seq = 82 },
	{ .name = "dvfsrc_sysfs", .seq = 82 },
	{ .name = "dvfsrc_debug_v2", .seq = 82 },
	{ .name = "mtk_icc_core", .seq = 83 },
	{ .name = "core", .seq = 83 },
	{ .name = "mmqos_common", .seq = 84 },
	{ .name = "mmqos_mtk", .seq = 84 },
	{ .name = "mmqos_hrt", .seq = 84 },
	{ .name = "mmqos_test", .seq = 84 },
	{ .name = "mmqos_vcp", .seq = 84 },
	{ .name = "mmqos_mt6899", .seq = 85 },
	{ .name = "mtk_cmdq_drv_ext", .seq = 86 },
	{ .name = "mtk_cmdq_mailbox_ext", .seq = 86 },
	{ .name = "mtk_cmdq_helper_ext", .seq = 86 },
	{ .name = "cmdq_util", .seq = 86 },
	{ .name = "cmdq_platform_mt6899", .seq = 87 },
	{ .name = "mtk_slbc", .seq = 88 },
	{ .name = "slbc", .seq = 88 },
	{ .name = "mtk_mml", .seq = 89 },
	{ .name = "mtk_mml_monitor", .seq = 89 },
	{ .name = "mtk_mml_driver", .seq = 89 },
	{ .name = "mtk_mml_core", .seq = 89 },
	{ .name = "mtk_mml_tile", .seq = 89 },
	{ .name = "mtk_mml_pq_core", .seq = 89 },
	{ .name = "mtk_mml_adaptor", .seq = 89 },
	{ .name = "mtk_mml_drm_adaptor", .seq = 89 },
	{ .name = "mtk_mml_dle_adaptor", .seq = 89 },
	{ .name = "mtk_mml_m2m_adaptor", .seq = 89 },
	{ .name = "mtk_mml_buf", .seq = 89 },
	{ .name = "mtk_mml_sys", .seq = 89 },
	{ .name = "tile_core", .seq = 89 },
	{ .name = "tile_mdp_func", .seq = 89 },
	{ .name = "dptilescaler", .seq = 89 },
	{ .name = "mtk_mml_aal", .seq = 89 },
	{ .name = "mtk_mml_color", .seq = 89 },
	{ .name = "mtk_mml_fg", .seq = 89 },
	{ .name = "mtk_mml_fg_fw", .seq = 89 },
	{ .name = "mtk_mml_hdr", .seq = 89 },
	{ .name = "mtk_mml_mutex", .seq = 89 },
	{ .name = "mtk_mml_rdma", .seq = 89 },
	{ .name = "mtk_mml_rsz", .seq = 89 },
	{ .name = "mtk_mml_rsz_fw", .seq = 89 },
	{ .name = "mtk_mml_pq_rdma", .seq = 89 },
	{ .name = "mtk_mml_pq_birsz", .seq = 89 },
	{ .name = "mtk_mml_pq_birsz_fw", .seq = 89 },
	{ .name = "mtk_mml_tcc", .seq = 89 },
	{ .name = "mtk_mml_tdshp", .seq = 89 },
	{ .name = "mtk_mml_wrot", .seq = 89 },
	{ .name = "mtk_mml_rrot", .seq = 89 },
	{ .name = "mtk_mml_merge", .seq = 89 },
	{ .name = "mtk_mml_c3d", .seq = 89 },
	{ .name = "mtk_mml_dpc", .seq = 89 },
	{ .name = "mtk_mml_scmi", .seq = 89 },
	{ .name = "mtk_mml_mmp", .seq = 89 },
	{ .name = "mtk_mml_test", .seq = 89 },
	{ .name = "mtk_mml_mt6899", .seq = 90 },
	{ .name = "mtk_mml_tp_mt6899", .seq = 90 },
	{ .name = "mdp_drv_dummy", .seq = 91 },
	{ .name = "leds_mtk", .seq = 92 },
	{ .name = "rt4831a_drv", .seq = 93 },
	{ .name = "mtk_panel_ext", .seq = 94 },
	{ .name = "mtk_mminfra_debug", .seq = 95 },
	{ .name = "mtk_afe_external", .seq = 96 },
	{ .name = "drm_dma_helper", .seq = 97 },
	{ .name = "drm_gem_dma_helper", .seq = 97 },
	{ .name = "drm_display_helper", .seq = 98 },
	{ .name = "drm_display_helper_mod", .seq = 98 },
	{ .name = "mediatek_drm", .seq = 99 },
	{ .name = "mtk_disp_aal", .seq = 99 },
	{ .name = "mtk_disp_ccorr", .seq = 99 },
	{ .name = "mtk_disp_color", .seq = 99 },
	{ .name = "mtk_disp_gamma", .seq = 99 },
	{ .name = "mtk_disp_ovl", .seq = 99 },
	{ .name = "mtk_disp_rdma", .seq = 99 },
	{ .name = "mtk_drm_crtc", .seq = 99 },
	{ .name = "mtk_drm_ddp", .seq = 99 },
	{ .name = "mtk_drm_ddp_comp", .seq = 99 },
	{ .name = "mtk_drm_drv", .seq = 99 },
	{ .name = "mtk_drm_gem", .seq = 99 },
	{ .name = "mtk_drm_plane", .seq = 99 },
	{ .name = "mtk_dsi", .seq = 99 },
	{ .name = "mtk_mipi_tx", .seq = 99 },
	{ .name = "mtk_mt8173_mipi_tx", .seq = 99 },
	{ .name = "mtk_mt8183_mipi_tx", .seq = 99 },
	{ .name = "mtk_dpi", .seq = 99 },
	{ .name = "mtk_drm_drv", .seq = 99 },
	{ .name = "mtk_disp_tdshp", .seq = 99 },
	{ .name = "mtk_disp_color", .seq = 99 },
	{ .name = "mtk_disp_ccorr", .seq = 99 },
	{ .name = "mtk_disp_c3d", .seq = 99 },
	{ .name = "mtk_disp_gamma", .seq = 99 },
	{ .name = "mtk_disp_aal", .seq = 99 },
	{ .name = "mtk_disp_dither", .seq = 99 },
	{ .name = "mtk_disp_chist", .seq = 99 },
	{ .name = "mtk_disp_ovl", .seq = 99 },
	{ .name = "mtk_disp_rdma", .seq = 99 },
	{ .name = "mtk_disp_mdp_rdma", .seq = 99 },
	{ .name = "mtk_disp_rsz", .seq = 99 },
	{ .name = "mtk_disp_mdp_rsz", .seq = 99 },
	{ .name = "mtk_disp_wdma", .seq = 99 },
	{ .name = "mtk_drm_crtc", .seq = 99 },
	{ .name = "mtk_drm_ddp", .seq = 99 },
	{ .name = "mtk_drm_ddp_addon", .seq = 99 },
	{ .name = "mtk_drm_ddp_comp", .seq = 99 },
	{ .name = "mtk_drm_fb", .seq = 99 },
	{ .name = "mtk_drm_gem", .seq = 99 },
	{ .name = "mtk_drm_plane", .seq = 99 },
	{ .name = "mtk_dsi", .seq = 99 },
	{ .name = "mtk_mipi_tx", .seq = 99 },
	{ .name = "mtk_writeback", .seq = 99 },
	{ .name = "mtk_fence", .seq = 99 },
	{ .name = "mtk_drm_session", .seq = 99 },
	{ .name = "mtk_dump", .seq = 99 },
	{ .name = "mtk_debug", .seq = 99 },
	{ .name = "mtk_layering_rule", .seq = 99 },
	{ .name = "mtk_layering_rule_base", .seq = 99 },
	{ .name = "mtk_rect", .seq = 99 },
	{ .name = "mtk_drm_mmp", .seq = 99 },
	{ .name = "mtk_drm_trace", .seq = 99 },
	{ .name = "mtk_drm_helper", .seq = 99 },
	{ .name = "mtk_drm_lowpower", .seq = 99 },
	{ .name = "mtk_disp_postmask", .seq = 99 },
	{ .name = "mtk_drm_assert", .seq = 99 },
	{ .name = "mtk_drm_fbconsole", .seq = 99 },
	{ .name = "mtk_disp_recovery", .seq = 99 },
	{ .name = "mtk_disp_pmqos", .seq = 99 },
	{ .name = "mtk_disp_dsc", .seq = 99 },
	{ .name = "mtk_disp_cm", .seq = 99 },
	{ .name = "mtk_disp_spr", .seq = 99 },
	{ .name = "mtk_disp_postalign", .seq = 99 },
	{ .name = "mtk_disp_oddmr_parse_data", .seq = 99 },
	{ .name = "mtk_disp_oddmr", .seq = 99 },
	{ .name = "mtk_drm_arr", .seq = 99 },
	{ .name = "mtk_disp_merge", .seq = 99 },
	{ .name = "mtk_dmdp_aal", .seq = 99 },
	{ .name = "mtk_fbconfig_kdebug", .seq = 99 },
	{ .name = "mtk_disp_y2r0", .seq = 99 },
	{ .name = "mtk_disp_dlo_async", .seq = 99 },
	{ .name = "mtk_disp_dli_async", .seq = 99 },
	{ .name = "mtk_disp_inlinerotate", .seq = 99 },
	{ .name = "mtk_mmlsys_bypass_mode", .seq = 99 },
	{ .name = "mtk_lease", .seq = 99 },
	{ .name = "mtk_drm_6835", .seq = 99 },
	{ .name = "mtk_disp_pq_helper", .seq = 99 },
	{ .name = "mtk_disp_vidle", .seq = 99 },
	{ .name = "mtk_disp_r2y0", .seq = 99 },
	{ .name = "mtk_disp_ovl_exdma", .seq = 99 },
	{ .name = "mtk_disp_ovl_blender", .seq = 99 },
	{ .name = "mtk_disp_ovl_outproc", .seq = 99 },
	{ .name = "mtk_disp_vdisp_ao", .seq = 99 },
	{ .name = "mtk_disp_splitter", .seq = 99 },
	{ .name = "mtk_drm_ddp_comp_auto", .seq = 99 },
	{ .name = "mtk_drm_crtc_auto", .seq = 99 },
	{ .name = "mtk_drm_debugfs", .seq = 99 },
	{ .name = "mtk_drm_dp_intf", .seq = 99 },
	{ .name = "mtk_drm_dp", .seq = 99 },
	{ .name = "mtk_drm_dp_mst_drv", .seq = 99 },
	{ .name = "mtk_drm_dp_mst", .seq = 99 },
	{ .name = "mtk_drm_dp_debug", .seq = 99 },
	{ .name = "mtk_dp_intf", .seq = 99 },
	{ .name = "mtk_dp", .seq = 99 },
	{ .name = "mtk_dp_hal", .seq = 99 },
	{ .name = "mtk_dp_debug", .seq = 99 },
	{ .name = "mtk_disp_bdg", .seq = 99 },
	{ .name = "mtk_dvo", .seq = 99 },
	{ .name = "mtk_cec", .seq = 99 },
	{ .name = "mtk_dpi", .seq = 99 },
	{ .name = "mi_disp_core", .seq = 99 },
	{ .name = "mi_disp_feature", .seq = 99 },
	{ .name = "mi_disp_file", .seq = 99 },
	{ .name = "mi_dsi_display", .seq = 99 },
	{ .name = "mi_dsi_panel", .seq = 99 },
	{ .name = "mi_disp_print", .seq = 99 },
	{ .name = "mi_disp_debugfs", .seq = 99 },
	{ .name = "mi_disp_sysfs", .seq = 99 },
	{ .name = "mi_disp_procfs", .seq = 99 },
	{ .name = "mi_disp_esd_check", .seq = 99 },
	{ .name = "mi_cooler_brightness_clone", .seq = 99 },
	{ .name = "mi_disp_notifier", .seq = 99 },
	{ .name = "mi_hwconf_manager", .seq = 99 },
	{ .name = "mi_disp_log", .seq = 99 },
	{ .name = "mi_disp_input_handler", .seq = 99 },
	{ .name = "mi_disp_boost", .seq = 99 },
	{ .name = "mi_drm_crtc", .seq = 99 },
	{ .name = "mi_disp_lhbm", .seq = 99 },
	{ .name = "panel_o10_36_02_0b_dsc_vdo", .seq = 100 },
	{ .name = "panel_o10_42_02_0a_dsc_vdo", .seq = 101 },
	{ .name = "panel_truly_td4330_cmd", .seq = 102 },
	{ .name = "panel_truly_nt35595_cmd", .seq = 103 },
	{ .name = "panel_alpha_jdi_nt36672e_vdo_60hz", .seq = 104 },
	{ .name = "panel_alpha_jdi_nt36672e_vdo_120hz_threshold", .seq = 105 },
	{ .name = "panel_alpha_jdi_nt36672e_vdo_120hz", .seq = 106 },
	{ .name = "panel_nt37801_cmd_120hz", .seq = 107 },
	{ .name = "panel_alpha_jdi_nt36672e_cphy_vdo", .seq = 108 },
	{ .name = "mtk_vdisp_v1", .seq = 109 },
	{ .name = "mtk_vdisp", .seq = 109 },
	{ .name = "mtk_vdisp_avs", .seq = 109 },
	{ .name = "mtk_dpc_v1", .seq = 110 },
	{ .name = "mtk_dpc_driver", .seq = 110 },
	{ .name = "mtk_dpc_mmp", .seq = 110 },
	{ .name = "aee_rs", .seq = 111 },
	{ .name = "mme", .seq = 112 },
	{ .name = "mmevent", .seq = 112 },
	{ .name = "mtk_uart_apdma", .seq = 113 },
	{ .name = "8250_mtk", .seq = 114 },
	{ .name = "mt6685_core", .seq = 115 },
	{ .name = "mt6685_audclk", .seq = 116 },
	{ .name = "mt6681_core", .seq = 117 },
	{ .name = "mt6681_auxadc", .seq = 118 },
	{ .name = "nvmem_mt6681_efuse", .seq = 119 },
	{ .name = "mt6681_efuse", .seq = 119 },
	{ .name = "clkbuf", .seq = 120 },
	{ .name = "clkbuf_ctrl", .seq = 120 },
	{ .name = "clkbuf_pmic", .seq = 120 },
	{ .name = "srclken", .seq = 120 },
	{ .name = "clkbuf_pmif", .seq = 120 },
	{ .name = "platform_hdlr", .seq = 120 },
	{ .name = "clkbuf_debug", .seq = 120 },
	{ .name = "dcxo_6357", .seq = 120 },
	{ .name = "dcxo_6358", .seq = 120 },
	{ .name = "dcxo_6358_tb", .seq = 120 },
	{ .name = "dcxo_6685", .seq = 120 },
	{ .name = "dcxo_6685_tb", .seq = 120 },
	{ .name = "dcxo_6359p", .seq = 120 },
	{ .name = "pmif_data_v1", .seq = 120 },
	{ .name = "src_data_v1", .seq = 120 },
	{ .name = "src_data_v2", .seq = 120 },
	{ .name = "ffa_v11", .seq = 121 },
	{ .name = "bus", .seq = 121 },
	{ .name = "driver", .seq = 121 },
	{ .name = "smccc", .seq = 121 },
	{ .name = "teeperf", .seq = 122 },
	{ .name = "main", .seq = 122 },
	{ .name = "user", .seq = 122 },
	{ .name = "mitee", .seq = 123 },
	{ .name = "mtk_spmi_pmic_adc", .seq = 124 },
	{ .name = "phy_mtk_xsphy", .seq = 125 },
	{ .name = "xhci_mtk_hcd_v2", .seq = 126 },
	{ .name = "xhci", .seq = 126 },
	{ .name = "xhci_mem", .seq = 126 },
	{ .name = "xhci_ext_caps", .seq = 126 },
	{ .name = "xhci_ring", .seq = 126 },
	{ .name = "xhci_hub", .seq = 126 },
	{ .name = "xhci_dbg", .seq = 126 },
	{ .name = "xhci_trace", .seq = 126 },
	{ .name = "xhci_mtk", .seq = 126 },
	{ .name = "xhci_mtk_sch", .seq = 126 },
	{ .name = "quirks", .seq = 126 },
	{ .name = "xhci_sideband", .seq = 126 },
	{ .name = "xhci_dbgcap", .seq = 126 },
	{ .name = "xhci_dbgtty", .seq = 126 },
	{ .name = "xhci_debugfs", .seq = 126 },
	{ .name = "mtu3", .seq = 127 },
	{ .name = "mtu3_plat", .seq = 127 },
	{ .name = "mtu3_trace", .seq = 127 },
	{ .name = "mtu3_host", .seq = 127 },
	{ .name = "mtu3_core", .seq = 127 },
	{ .name = "mtu3_gadget_ep0", .seq = 127 },
	{ .name = "mtu3_gadget", .seq = 127 },
	{ .name = "mtu3_qmu", .seq = 127 },
	{ .name = "mtu3_dr", .seq = 127 },
	{ .name = "mtu3_debugfs", .seq = 127 },
	{ .name = "usb_boost", .seq = 128 },
	{ .name = "usb_boost_common", .seq = 128 },
	{ .name = "usb_boost_plat", .seq = 128 },
	{ .name = "mux_switch", .seq = 129 },
	{ .name = "ps5170", .seq = 130 },
	{ .name = "usb_dp_selector", .seq = 131 },
	{ .name = "blocktag", .seq = 132 },
	{ .name = "blocktag_mictx", .seq = 132 },
	{ .name = "blocktag_core", .seq = 132 },
	{ .name = "blocktag_earaio", .seq = 132 },
	{ .name = "cqhci", .seq = 133 },
	{ .name = "cqhci_core", .seq = 133 },
	{ .name = "mtk_mmc_dbg", .seq = 134 },
	{ .name = "hwid", .seq = 135 },
	{ .name = "ufs_mediatek_dbg", .seq = 136 },
	{ .name = "mpbe", .seq = 137 },
	{ .name = "rpmb", .seq = 138 },
	{ .name = "core", .seq = 138 },
	{ .name = "ufs_mediatek_mod", .seq = 139 },
	{ .name = "ufs_mediatek_perf", .seq = 139 },
	{ .name = "ufs_mediatek_sysfs", .seq = 139 },
	{ .name = "ufs_mediatek_mimic", .seq = 139 },
	{ .name = "ufs_mediatek_mbrain", .seq = 139 },
	{ .name = "ufs_mediatek", .seq = 139 },
	{ .name = "rpmb_mtk", .seq = 140 },
	{ .name = "mtk_mmc", .seq = 141 },
	{ .name = "phy_mtk_ufs", .seq = 142 },
	{ .name = "mi_memory", .seq = 143 },
	{ .name = "pidmap", .seq = 144 },
	{ .name = "mtk_pmic_keys", .seq = 145 },
	{ .name = "mtk_i3c_master_mt69xx", .seq = 146 },
	{ .name = "mtk_i3c_i2c_wrap", .seq = 147 },
	{ .name = "spi_mt65xx", .seq = 148 },
	{ .name = "mt6375", .seq = 149 },
	{ .name = "extdev_io_class", .seq = 150 },
	{ .name = "rt4803", .seq = 151 },
	{ .name = "rt5133_regulator", .seq = 152 },
	{ .name = "rt6160_regulator", .seq = 153 },
	{ .name = "rtc_mt6685", .seq = 154 },
	{ .name = "kfifo_buf", .seq = 155 },
	{ .name = "industrialio_triggered_buffer", .seq = 156 },
	{ .name = "mt6375_adc", .seq = 157 },
	{ .name = "mt6375_auxadc", .seq = 158 },
	{ .name = "adapter_class", .seq = 159 },
	{ .name = "charger_class", .seq = 160 },
	{ .name = "mtk_charger_algorithm_class", .seq = 161 },
	{ .name = "pd_dbg_info", .seq = 162 },
	{ .name = "tcpc_class", .seq = 163 },
	{ .name = "tcpci_core", .seq = 163 },
	{ .name = "tcpci_typec", .seq = 163 },
	{ .name = "tcpci_timer", .seq = 163 },
	{ .name = "tcpm", .seq = 163 },
	{ .name = "tcpci", .seq = 163 },
	{ .name = "tcpci_alert", .seq = 163 },
	{ .name = "rt_regmap", .seq = 163 },
	{ .name = "tcpci_event", .seq = 163 },
	{ .name = "pd_core", .seq = 163 },
	{ .name = "pd_policy_engine", .seq = 163 },
	{ .name = "pd_process_evt", .seq = 163 },
	{ .name = "pd_dpm_core", .seq = 163 },
	{ .name = "pd_dpm_alt_mode_dp", .seq = 163 },
	{ .name = "pd_dpm_pdo_select", .seq = 163 },
	{ .name = "pd_dpm_reaction", .seq = 163 },
	{ .name = "pd_process_evt_snk", .seq = 163 },
	{ .name = "pd_process_evt_src", .seq = 163 },
	{ .name = "pd_process_evt_vdm", .seq = 163 },
	{ .name = "pd_process_evt_drs", .seq = 163 },
	{ .name = "pd_process_evt_prs", .seq = 163 },
	{ .name = "pd_process_evt_vcs", .seq = 163 },
	{ .name = "pd_process_evt_dbg", .seq = 163 },
	{ .name = "pd_process_evt_tcp", .seq = 163 },
	{ .name = "pd_process_evt_com", .seq = 163 },
	{ .name = "pd_policy_engine_src", .seq = 163 },
	{ .name = "pd_policy_engine_snk", .seq = 163 },
	{ .name = "pd_policy_engine_ufp", .seq = 163 },
	{ .name = "pd_policy_engine_vcs", .seq = 163 },
	{ .name = "pd_policy_engine_dfp", .seq = 163 },
	{ .name = "pd_policy_engine_dr", .seq = 163 },
	{ .name = "pd_policy_engine_drs", .seq = 163 },
	{ .name = "pd_policy_engine_prs", .seq = 163 },
	{ .name = "pd_policy_engine_dbg", .seq = 163 },
	{ .name = "pd_policy_engine_com", .seq = 163 },
	{ .name = "bq28z610", .seq = 164 },
	{ .name = "mtk_charger_framework", .seq = 165 },
	{ .name = "mtk_charger", .seq = 165 },
	{ .name = "mtk_charger_intf", .seq = 165 },
	{ .name = "mtk_basic_charger", .seq = 165 },
	{ .name = "mtk_pulse_charger", .seq = 165 },
	{ .name = "mtk_adapter_switch", .seq = 165 },
	{ .name = "pmic_voter", .seq = 165 },
	{ .name = "step_jeita_charge", .seq = 165 },
	{ .name = "charger_partition", .seq = 165 },
	{ .name = "mt6375_charger", .seq = 166 },
	{ .name = "tcpc_mt6375", .seq = 167 },
	{ .name = "mtk_chg_type_det", .seq = 168 },
	{ .name = "mtk_pd_adapter", .seq = 169 },
	{ .name = "mtk_pep40", .seq = 170 },
	{ .name = "mtk_pe4", .seq = 170 },
	{ .name = "mtk_pe4_hal", .seq = 170 },
	{ .name = "mtk_pep45", .seq = 171 },
	{ .name = "mtk_pe4_5", .seq = 171 },
	{ .name = "mtk_pe4_5_hal", .seq = 171 },
	{ .name = "mtk_pd_charging", .seq = 172 },
	{ .name = "mtk_pd", .seq = 172 },
	{ .name = "mtk_pd_hal", .seq = 172 },
	{ .name = "mtk_pep20", .seq = 173 },
	{ .name = "mtk_pe2", .seq = 173 },
	{ .name = "mtk_pe2_hal", .seq = 173 },
	{ .name = "mtk_pep", .seq = 174 },
	{ .name = "mtk_pe", .seq = 174 },
	{ .name = "mtk_pe_hal", .seq = 174 },
	{ .name = "hl7603", .seq = 175 },
	{ .name = "sc858x_charger", .seq = 176 },
	{ .name = "bq25985_charger", .seq = 177 },
	{ .name = "pd_single_cp_manager", .seq = 178 },
	{ .name = "rt_pd_manager", .seq = 179 },
	{ .name = "pmic_lbat_service", .seq = 180 },
	{ .name = "pmic_lvsys_notify", .seq = 181 },
	{ .name = "mtk_low_battery_throttling", .seq = 182 },
	{ .name = "mt6375_battery", .seq = 183 },
	{ .name = "mtk_battery_coulomb_service", .seq = 183 },
	{ .name = "mtk_battery", .seq = 183 },
	{ .name = "mtk_battery_algo", .seq = 183 },
	{ .name = "mt6375_gauge", .seq = 183 },
	{ .name = "mtk_battery_daemon", .seq = 183 },
	{ .name = "mtk_battery_interface", .seq = 183 },
	{ .name = "xm_power", .seq = 184 },
	{ .name = "pwm_mtk_disp", .seq = 185 },
	{ .name = "phy_mtk_pcie", .seq = 186 },
	{ .name = "pcie_mediatek_gen3", .seq = 187 },
	{ .name = "leds_aw21024", .seq = 188 },
	{ .name = "leds_mtk_disp", .seq = 189 },
	{ .name = "leds_mtk_pwm", .seq = 190 },
	{ .name = "extcon_mtk_usb", .seq = 191 },
	{ .name = "tcpci_late_sync", .seq = 192 },
	{ .name = "mtk_mminfra_imax", .seq = 193 },
	{ .name = "mtk_battery_manager", .seq = 194 },
	{ .name = "mtk_battery_interface", .seq = 194 },
	{ .name = "reset_ti_syscon", .seq = 195 },
	{ .name = "adsp", .seq = 196 },
	{ .name = "adsp_core", .seq = 196 },
	{ .name = "adsp_fs", .seq = 196 },
	{ .name = "adsp_semaphore", .seq = 196 },
	{ .name = "adsp_logger", .seq = 196 },
	{ .name = "adsp_feature_table", .seq = 196 },
	{ .name = "adsp_timesync", .seq = 196 },
	{ .name = "adsp_awake", .seq = 196 },
	{ .name = "adsp_reserved_mem", .seq = 196 },
	{ .name = "adsp_platform", .seq = 196 },
	{ .name = "adsp_mbox", .seq = 196 },
	{ .name = "adsp_platform_driver", .seq = 196 },
	{ .name = "adsp_excep", .seq = 196 },
	{ .name = "adsp_qos", .seq = 196 },
	{ .name = "adsp_bus_monitor", .seq = 196 },
	{ .name = "adsp_ipic", .seq = 196 },
	{ .name = "adsp_dbg_dump", .seq = 196 },
	{ .name = "adsp_dbg", .seq = 196 },
	{ .name = "slbc_ipi", .seq = 197 },
	{ .name = "slbc_trace", .seq = 198 },
	{ .name = "arm_dsu_pmu", .seq = 199 },
	{ .name = "mtk_swpm_perf_arm_pmu", .seq = 200 },
	{ .name = "swpm_perf_arm_pmu", .seq = 200 },
	{ .name = "emi_mpu", .seq = 201 },
	{ .name = "smpu", .seq = 202 },
	{ .name = "smpu_hook_v1", .seq = 203 },
	{ .name = "emi_slb", .seq = 204 },
	{ .name = "slc_parity", .seq = 205 },
	{ .name = "usb_meta", .seq = 206 },
	{ .name = "mediatek_cpufreq_hw", .seq = 207 },
	{ .name = "mediatek_cpufreq_hw_main", .seq = 207 },
	{ .name = "mediatek_cpufreq_hw_fdvfs", .seq = 207 },
	{ .name = "dbg_error_flag", .seq = 208 },
	{ .name = "bus_parity", .seq = 209 },
	{ .name = "mtk_socinfo", .seq = 210 },
	{ .name = "last_bus", .seq = 211 },
	{ .name = "cache_parity", .seq = 212 },
	{ .name = "systracker", .seq = 213 },
	{ .name = "crash_module", .seq = 214 },
	{ .name = "mtd", .seq = 215 },
	{ .name = "mtdcore", .seq = 215 },
	{ .name = "mtdsuper", .seq = 215 },
	{ .name = "mtdconcat", .seq = 215 },
	{ .name = "mtdpart", .seq = 215 },
	{ .name = "mtdchar", .seq = 215 },
	{ .name = "mtd_blkdevs", .seq = 216 },
	{ .name = "ofpart", .seq = 217 },
	{ .name = "ofpart_core", .seq = 217 },
	{ .name = "mtdoops", .seq = 218 },
	{ .name = "block2mtd", .seq = 219 },
	{ .name = "chipreg", .seq = 220 },
	{ .name = "mtdblock", .seq = 221 },
	{ .name = "debug_ext", .seq = 222 },
	{ .name = "scene_swappiness", .seq = 223 },
	{ .name = "simtray", .seq = 224 },
	{ .name = "mtk_scpsys_mt6893", .seq = 1000 },
	{ .name = "mt6397", .seq = 1001 },
	{ .name = "cmdq_sec_drv", .seq = 1002 },
	{ .name = "gz_trusty_mod", .seq = 1003 },
	{ .name = "gz_log_mod", .seq = 1004 },
	{ .name = "mtk_gpu_hal", .seq = 1005 },
	{ .name = "mtk_gpu_qos", .seq = 1006 },
	{ .name = "clk_dbg_mt6899", .seq = 1007 },
	{ .name = "mtk_scpsys_mt6768", .seq = 1008 },
	{ .name = "mtk_scpsys_mt6765", .seq = 1009 },
	{ .name = "mtk_scpsys_mt6877", .seq = 1010 },
	{ .name = "mtk_emibus_icc", .seq = 1011 },
	{ .name = "mtk_swpm_dbg_v6899", .seq = 1095 },
	{ .name = "sspm_v3", .seq = 1013 },
	{ .name = "richtek_spm_cls", .seq = 1014 },
	{ .name = "vdec_fmt", .seq = 1015 },
	{ .name = "mtk_cm_mgr_mt6899", .seq = 1016 },
	{ .name = "gz_ipc_mod", .seq = 1017 },
	{ .name = "hf_manager", .seq = 1018 },
	{ .name = "ccci_util_lib", .seq = 1019 },
	{ .name = "mtk_lpm_dbg_common_v2", .seq = 1020 },
	{ .name = "mtk_lpm_plat_v2", .seq = 1021 },
	{ .name = "fhctl", .seq = 1022 },
	{ .name = "iommu_test", .seq = 1023 },
	{ .name = "iommu_gz", .seq = 1024 },
	{ .name = "mtk_heap_refill", .seq = 1025 },
	{ .name = "mtk_sec_heap", .seq = 1026 },
	{ .name = "mtk_heap_debug", .seq = 1027 },
	{ .name = "mtk_scpsys_mt6761", .seq = 1028 },
	{ .name = "mtk_scpsys_mt6781", .seq = 1029 },
	{ .name = "mtk_scpsys_mt6833", .seq = 1030 },
	{ .name = "mtk_scpsys_mt6853", .seq = 1031 },
	{ .name = "mtk_scpsys_mt6991_spm", .seq = 1032 },
	{ .name = "mtk_scpsys_mt6991_mmpc", .seq = 1033 },
	{ .name = "nvmem_mt635x_efuse", .seq = 1034 },
	{ .name = "mtk_extbuck_debug", .seq = 1035 },
	{ .name = "wl2866d", .seq = 1036 },
	{ .name = "sgm38121", .seq = 1037 },
	{ .name = "mtk_aod_scp", .seq = 1038 },
	{ .name = "mtk_disp_sec", .seq = 1039 },
	{ .name = "mtk_mml_mt6991", .seq = 1040 },
	{ .name = "mediatek_drm_gateic", .seq = 1041 },
	{ .name = "mediatek_drm_panel_drv", .seq = 1042 },
	{ .name = "mediatek_cust_panel_sample", .seq = 1043 },
	{ .name = "mt63xx_debug", .seq = 1044 },
	{ .name = "mtk_spmi_pmic_debug", .seq = 1045 },
	{ .name = "mt635x_auxadc", .seq = 1046 },
	{ .name = "spmi_mtk_mpu", .seq = 1047 },
	{ .name = "emi_fake_eng", .seq = 1048 },
	{ .name = "mtk_ufcs_adapter", .seq = 1049 },
	{ .name = "cmdq_test", .seq = 1050 },
	{ .name = "mtk_mmdvfs_v3_start", .seq = 1051 },
	{ .name = "mtk_battery_oc_throttling", .seq = 1052 },
	{ .name = "mtk_bp_thl", .seq = 1053 },
	{ .name = "mtk_dynamic_loading_throttling", .seq = 1054 },
	{ .name = "mtk_md_power_throttling", .seq = 1055 },
	{ .name = "mtk_cpu_power_throttling", .seq = 1056 },
	{ .name = "mtk_gpu_power_throttling", .seq = 1057 },
	{ .name = "slbc_mt6899", .seq = 1058 },
	{ .name = "mtk_perf_ioctl", .seq = 1059 },
	{ .name = "mtk_ioctl_touch_boost", .seq = 1060 },
	{ .name = "mtk_ioctl_powerhal", .seq = 1061 },
	{ .name = "mtk_perf_ioctl_magt", .seq = 1062 },
	{ .name = "mtk_game", .seq = 1063 },
	{ .name = "mtk_fpsgo", .seq = 1064 },
	{ .name = "load_track", .seq = 1065 },
	{ .name = "uload_ind", .seq = 1066 },
	{ .name = "mtk_mdpm", .seq = 1067 },
	{ .name = "mtk_pbm", .seq = 1068 },
	{ .name = "mtk_peak_power_budget", .seq = 1069 },
	{ .name = "sec", .seq = 1070 },
	{ .name = "kshrink_slabd", .seq = 1071 },
	{ .name = "snd_soc_mtk_common", .seq = 1072 },
	{ .name = "mtk_btcvsd", .seq = 1073 },
	{ .name = "mddp", .seq = 1074 },
	{ .name = "mtk_vmm_notifier", .seq = 1075 },
	{ .name = "mcupm", .seq = 1076 },
	{ .name = "trace_mmstat", .seq = 1077 },
	{ .name = "elliptic_ultrasound", .seq = 1078 },
	{ .name = "mtk_pmic_oc_debug", .seq = 1079 },
	{ .name = "nxp_i2c", .seq = 1080 },
	{ .name = "p73", .seq = 1081 },
	{ .name = "flashlight", .seq = 1082 },
	{ .name = "lm3644", .seq = 1083 },
	{ .name = "ocp81377", .seq = 1084 },
	{ .name = "dw9781c", .seq = 1085 },
	{ .name = "dw9781d", .seq = 1086 },
	{ .name = "main_vcm", .seq = 1087 },
	{ .name = "main2_vcm", .seq = 1088 },
	{ .name = "main3_vcm", .seq = 1089 },
	{ .name = "main4_vcm", .seq = 1090 },
	{ .name = "sub_vcm", .seq = 1091 },
	{ .name = "c2k_usb", .seq = 1092 },
	{ .name = "mtk_u_ether", .seq = 1093 },
	{ .name = "usb_logger", .seq = 1094 },
	{ .name = "usb_offload", .seq = 1120 },
	{ .name = "met_gpu_api", .seq = 1096 },
	{ .name = "met_gpu_adv_api", .seq = 1097 },
	{ .name = "met_vcore_api", .seq = 1098 },
	{ .name = "met_backlight_api", .seq = 1099 },
	{ .name = "met_emi_api", .seq = 1100 },
	{ .name = "met_sspm_api", .seq = 1101 },
	{ .name = "met_mcupm_api", .seq = 1102 },
	{ .name = "met_gpueb_api", .seq = 1103 },
	{ .name = "met_ipi_api", .seq = 1104 },
	{ .name = "met_scmi_api", .seq = 1105 },
	{ .name = "snd_soc_mt6899_afe", .seq = 1106 },
	{ .name = "mt6899_mt6368", .seq = 1107 },
	{ .name = "snd_soc_audiodsp_common", .seq = 1121 },
	{ .name = "mtk_soc_offload_common", .seq = 1109 },
	{ .name = "mtk_scp_vow", .seq = 1110 },
	{ .name = "mtk_vow", .seq = 1111 },
	{ .name = "snd_soc_mtk_scp_ultra", .seq = 1112 },
	{ .name = "mtk_scp_ultra", .seq = 1113 },
	{ .name = "snd_soc_mt6368", .seq = 1114 },
	{ .name = "mt6368_accdet", .seq = 1115 },
	{ .name = "snd_soc_rt5512", .seq = 1116 },
	{ .name = "snd_soc_tfa98xx", .seq = 1117 },
	{ .name = "tmem_ffa", .seq = 1118 },
	{ .name = "adsp_v2", .seq = 1119 },
	{ .name = "jpeg_driver", .seq = 1120 },
	{ .name = "widevine_driver", .seq = 1121 },
	{ .name = "gz_main_mod", .seq = 1122 },
	{ .name = "gz_tz_system", .seq = 1123 },
	{ .name = "gz_irq_mod", .seq = 1124 },
	{ .name = "gz_virtio_mod", .seq = 1125 },
	{ .name = "ccmni", .seq = 1126 },
	{ .name = "mtk_vcodec_dec_v2", .seq = 1127 },
	{ .name = "mtk_vcodec_enc_v2", .seq = 1128 },
	{ .name = "haptic", .seq = 1129 },
	{ .name = "si_haptic", .seq = 1130 },
	{ .name = "aac_haptic", .seq = 1131 },
	{ .name = "ged", .seq = 1132 },
	{ .name = "mtk_gpufreq_wrapper", .seq = 1133 },
	{ .name = "mtk_gpufreq_mt6899", .seq = 1134 },
	{ .name = "mtk_gpueb", .seq = 1135 },
	{ .name = "mtk_ghpm", .seq = 1136 },
	{ .name = "mtk_ghpm_swwa", .seq = 1137 },
	{ .name = "mtk_cg_peak_power_throttling", .seq = 1139 },
	{ .name = "mtk_jpeg", .seq = 1140 },
	{ .name = "pgboost", .seq = 1141 },
	{ .name = "pmsr_v3", .seq = 1142 },
	{ .name = "mtk_cam_isp8", .seq = 1143 },
	{ .name = "mtk_hcp_isp8", .seq = 1144 },
	{ .name = "mtk_img_frm_sync", .seq = 1145 },
	{ .name = "camera_dpe_isp8", .seq = 1146 },
	{ .name = "mtk_imgsys_cmdq_isp8", .seq = 1147 },
	{ .name = "soc_temp_lvts", .seq = 1148 },
	{ .name = "pmic_temp", .seq = 1149 },
	{ .name = "md_cooling_all", .seq = 1150 },
	{ .name = "charger_cooling", .seq = 1151 },
	{ .name = "backlight_cooling", .seq = 1152 },
	{ .name = "thermal_trace", .seq = 1153 },
	{ .name = "thermal_interface", .seq = 1154 },
	{ .name = "board_temp", .seq = 1155 },
	{ .name = "vtskin_temp", .seq = 1156 },
	{ .name = "wifi_cooling", .seq = 1157 },
	{ .name = "met", .seq = 1158 },
	{ .name = "camera_eeprom_v4l2", .seq = 1159 },
	{ .name = "mtk_mae", .seq = 1160 },
	{ .name = "mtk_imgsys_isp8", .seq = 1161 },
	{ .name = "mtk_mae_isp8", .seq = 1162 },
	{ .name = "mtk_ipesys_me", .seq = 1163 },
	{ .name = "pda_drv_mt6899", .seq = 1164 },
	{ .name = "mtk_c2ps", .seq = 1165 },
	{ .name = "c2ps_perf_ioctl", .seq = 1166 },
	{ .name = "mtk_ccuv", .seq = 1138 },
	{ .name = "mtk_ips_helper", .seq = 1168 },
	{ .name = "cam_log", .seq = 1169 },
	{ .name = "mtk_mbraink", .seq = 1170 },
	{ .name = "mtk_mbraink_v6899", .seq = 1171 },
	{ .name = "mtk_mbraink_bridge", .seq = 1172 },
	{ .name = "ccci_auxadc", .seq = 1028 },
	{ .name = "ccci_md_all", .seq = 1029 },
	{ .name = "ccci_fsm_scp", .seq = 1032 },
	{ .name = "ccci_ccif", .seq = 1030 },
	{ .name = "ccci_dpmaif", .seq = 1031 },
	{ .name = "audio_ipi", .seq = 1120 },
	{ .name = "mtk_lpm_dbg_mt6899", .seq = 1179 },
	{ .name = "lpm_gov_mhsp", .seq = 1180 },
	{ .name = "mtk_ssc", .seq = 1181 },
	{ .name = "mtk_ssc_dbg_v2", .seq = 1182 },
	{ .name = "wla_v1", .seq = 1183 },
	{ .name = "wla_v1_dbg", .seq = 1184 },
	{ .name = "atf_logger", .seq = 1185 },
	{ .name = "mtk_pwm", .seq = 1186 },
	{ .name = "mtk_aov", .seq = 1187 },
	{ .name = "apu_top", .seq = 1188 },
	{ .name = "apusys", .seq = 1189 },
	{ .name = "sapu", .seq = 1190 },
	{ .name = "mali_kbase_mt6899_r49", .seq = 1191 },
	{ .name = "mali_mgm_mt6899_r49", .seq = 1192 },
	{ .name = "mali_prot_alloc_mt6899_r49", .seq = 1193 },
	{ .name = "mtk_core_ctl", .seq = 1194 },
	{ .name = "cpuqos_v3", .seq = 1195 },
	{ .name = "task_turbo", .seq = 1196 },
	{ .name = "cpudvfs", .seq = 1197 },
	{ .name = "hbt", .seq = 1198 },
	{ .name = "scp", .seq = 1071 },
	{ .name = "connscp", .seq = 1211 },
	{ .name = "connfem", .seq = 1212 },
	{ .name = "conninfra", .seq = 1213 },
	{ .name = "wmt_chrdev_wifi_connac2", .seq = 1214 },
	{ .name = "wlan_drv_gen4m_6899", .seq = 1215 },
	{ .name = "fmradio_drv_connac2x", .seq = 1216 },
	{ .name = "gps_drv_dl_v051", .seq = 1217 },
	{ .name = "bt_drv_6899", .seq = 1218 },
	{ .name = "gps_scp", .seq = 1219 },
	{ .name = "gps_pwr", .seq = 1220 },
	{ .name = "mi_gps_pwr", .seq = 1221 },
	{ .name = "sensorhub", .seq = 1222 },
	{ .name = "mtk_swpm", .seq = 1223 },
	{ .name = "mtk_lpm", .seq = 1224 },
	{ .name = "frs", .seq = 1225 },
	{ .name = "powerhal_cpu_ctrl", .seq = 1226 },
	{ .name = "touch_boost", .seq = 1227 },
	{ .name = "mtk_et", .seq = 1228 },
	{ .name = "mtk_composite", .seq = 1229 },
	{ .name = "et7480", .seq = 1230 },
	{ .name = "mtk_qos", .seq = 1231 },
	{ .name = "mtk_ccd_remoteproc", .seq = 1232 },
	{ .name = "imgsensor_glue_isp8", .seq = 1233 },
	{ .name = "imgsensor_isp8", .seq = 1234 },
	{ .name = "camera_af_media", .seq = 1235 },
	{ .name = "mtk_irtx_pwm", .seq = 1236 },
	{ .name = "cpufreq_sugov_ext", .seq = 1237 },
	{ .name = "scheduler", .seq = 1238 },
	{ .name = "clk_disable_unused", .seq = 1239 },
	{ .name = "mtk_dvfsrc_start", .seq = 1240 },
	{ .name = "mtk_pm_domain_disable_unused", .seq = 1241 },
	{ .name = "mtk_swpm_cpu_dbg_v6899", .seq = 1242 },
	{ .name = "mtk_perf_common", .seq = 1243 },
	{ .name = "mi_mem_engine", .seq = 1244 },
	{ .name = "mi_log", .seq = 1245 },
	{ .name = "mi_thermal_interface", .seq = 1246 },
	{ .name = "powersave", .seq = 1247 },
	{ .name = "unionpower", .seq = 1248 },
	{ .name = "binder_prio", .seq = 1249 },
	{ .name = "cpu_isolate_cooling", .seq = 1250 },
	{ .name = "mi_exception_log", .seq = 1251 },
	{ .name = "xiaomi_spi_tee", .seq = 1252 },
	/* ---- rodin b567: touch 三件 =y（第六十九轮）。6.6 装载位 = vendor_dlkm
	 * modules.load 行 211/212/213，框架先于 IC（212/213 依赖 211 的导出）；
	 * scp=1071 之后（goodix/focaltech scp_tp_init 消费 scp_ipidev/mtk_ipi_*），
	 * miev=23 早已就绪（框架消费 cdev_tevent_*）。段尾续编 1253-1255。 */
	{ .name = "xiaomi_touch_rodin", .seq = 1253 },
	{ .name = "goodix_core_rodin", .seq = 1254 },
	{ .name = "focaltech_touch_rodin", .seq = 1255 },
};

const unsigned int __vseq_mod_order_nr =
	sizeof(__vseq_mod_order) / sizeof(__vseq_mod_order[0]);
